// <auto-generated />
using System;
using DevOpsDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevOpsDemo.Data.Migrations
{
    [DbContext(typeof(DevOpsDemoContext))]
    [Migration("20251120112759_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ActorMovie", b =>
                {
                    b.Property<int>("ActorID")
                        .HasColumnType("int");

                    b.Property<int>("MovieID")
                        .HasColumnType("int");

                    b.HasKey("ActorID", "MovieID");

                    b.HasIndex("MovieID");

                    b.ToTable("MovieActor", (string)null);
                });

            modelBuilder.Entity("DevOpsDemo.Data.Models.Actor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Actor");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            FirstName = "Samuel L.",
                            LastName = "Jackson"
                        },
                        new
                        {
                            ID = 2,
                            FirstName = "Anya",
                            LastName = "Taylor-Joy"
                        },
                        new
                        {
                            ID = 3,
                            FirstName = "Chris",
                            LastName = "Pratt"
                        },
                        new
                        {
                            ID = 4,
                            FirstName = "Elizabeth",
                            LastName = "Banks"
                        },
                        new
                        {
                            ID = 5,
                            FirstName = "Chris",
                            LastName = "Evans"
                        },
                        new
                        {
                            ID = 6,
                            FirstName = "Robert",
                            LastName = "Downey JR"
                        },
                        new
                        {
                            ID = 7,
                            FirstName = "Leonardo",
                            LastName = "Di Caprio"
                        },
                        new
                        {
                            ID = 8,
                            FirstName = "Kate",
                            LastName = "Winslet"
                        },
                        new
                        {
                            ID = 9,
                            FirstName = "Al",
                            LastName = "Pacino"
                        },
                        new
                        {
                            ID = 10,
                            FirstName = "Michelle",
                            LastName = "Pfeiffer"
                        },
                        new
                        {
                            ID = 11,
                            FirstName = "Bruce",
                            LastName = "Willis"
                        },
                        new
                        {
                            ID = 12,
                            FirstName = "John",
                            LastName = "Travolta"
                        },
                        new
                        {
                            ID = 13,
                            FirstName = "Cristian",
                            LastName = "Bale"
                        },
                        new
                        {
                            ID = 14,
                            FirstName = "Heath",
                            LastName = "Ledger"
                        },
                        new
                        {
                            ID = 15,
                            FirstName = "Gary",
                            LastName = "Oldman"
                        },
                        new
                        {
                            ID = 16,
                            FirstName = "Morgan",
                            LastName = "Freeman"
                        },
                        new
                        {
                            ID = 17,
                            FirstName = "Paul",
                            LastName = "Newman"
                        },
                        new
                        {
                            ID = 18,
                            FirstName = "Robert",
                            LastName = "Redford"
                        },
                        new
                        {
                            ID = 19,
                            FirstName = "Tom",
                            LastName = "Hanks"
                        },
                        new
                        {
                            ID = 20,
                            FirstName = "Tim",
                            LastName = "Allen"
                        });
                });

            modelBuilder.Entity("DevOpsDemo.Data.Models.Director", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Director");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            FirstName = "M. Night",
                            LastName = "Shyamalan"
                        },
                        new
                        {
                            ID = 2,
                            FirstName = "Mike",
                            LastName = "Mitchell"
                        },
                        new
                        {
                            ID = 3,
                            FirstName = "Joss",
                            LastName = "Whedan"
                        },
                        new
                        {
                            ID = 4,
                            FirstName = "James",
                            LastName = "Cameron"
                        },
                        new
                        {
                            ID = 5,
                            FirstName = "Brian",
                            LastName = "de Palma"
                        },
                        new
                        {
                            ID = 6,
                            FirstName = "Quentin",
                            LastName = "Tarantino"
                        },
                        new
                        {
                            ID = 7,
                            FirstName = "Christopher",
                            LastName = "Nolan"
                        },
                        new
                        {
                            ID = 8,
                            FirstName = "George",
                            LastName = "Roy Hill"
                        },
                        new
                        {
                            ID = 9,
                            FirstName = "John",
                            LastName = "Lasseter"
                        });
                });

            modelBuilder.Entity("DevOpsDemo.Data.Models.Movie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("DirectorID")
                        .HasColumnType("int");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("TrailerUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DirectorID");

                    b.ToTable("Movie");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Security guard David Dunn uses his supernatural abilities to track Kevin Wendell Crumb, a disturbed man who has twenty-four personalities.",
                            DirectorID = 1,
                            ImgUrl = "https://m.media-amazon.com/images/M/MV5BMTY1OTA2MjI5OV5BMl5BanBnXkFtZTgwNzkxMjU4NjM@._V1_UY209_CR3,0,140,209_AL_.jpg",
                            Name = "Glass (Cristal)",
                            TrailerUrl = "https://www.imdb.com/list/ls025720609/videoplayer/vi3625105945",
                            Year = 2019
                        },
                        new
                        {
                            ID = 2,
                            Description = "It's been five years since everything was awesome and the citizens are facing a huge new threat: Lego Duplo invaders from outer space, wrecking everything faster than they can rebuild.",
                            DirectorID = 2,
                            ImgUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuTdlUB6pjd1AQAwx5kgLP6EF8egNCu_XoMcB3_mRsHHYF4iUg",
                            Name = "La LEGO película 2",
                            TrailerUrl = "https://www.youtube.com/watch?v=WPiQJyTwOPY",
                            Year = 2019
                        },
                        new
                        {
                            ID = 3,
                            Description = "Earth's mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity.",
                            DirectorID = 3,
                            ImgUrl = "https://images-na.ssl-images-amazon.com/images/I/71FjI%2B8ewWL._SY445_.jpg",
                            Name = "The Avengers",
                            TrailerUrl = "https://www.imdb.com/title/tt0848228/videoplayer/vi1891149081",
                            Year = 2012
                        },
                        new
                        {
                            ID = 4,
                            Description = "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.",
                            DirectorID = 4,
                            ImgUrl = "https://m.media-amazon.com/images/M/MV5BMDdmZGU3NDQtY2E5My00ZTliLWIzOTUtMTY4ZGI1YjdiNjk3XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_UX182_CR0,0,182,268_AL_.jpg",
                            Name = "Titanic",
                            TrailerUrl = "https://www.imdb.com/title/tt0120338/videoplayer/vi907189785",
                            Year = 1997
                        },
                        new
                        {
                            ID = 5,
                            Description = "In 1980 Miami, a determined Cuban immigrant takes over a drug cartel and succumbs to greed.",
                            DirectorID = 5,
                            ImgUrl = "https://m.media-amazon.com/images/M/MV5BNjdjNGQ4NDEtNTEwYS00MTgxLTliYzQtYzE2ZDRiZjFhZmNlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX182_CR0,0,182,268_AL_.jpg",
                            Name = "Scarface",
                            TrailerUrl = "https://www.imdb.com/title/tt0086250/videoplayer/vi3939802137",
                            Year = 1983
                        },
                        new
                        {
                            ID = 6,
                            Description = "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
                            DirectorID = 6,
                            ImgUrl = "https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UY268_CR1,0,182,268_AL_.jpg",
                            Name = "Pulp fiction",
                            TrailerUrl = "https://www.imdb.com/title/tt0110912/videoplayer/vi2620371481",
                            Year = 1994
                        },
                        new
                        {
                            ID = 7,
                            Description = "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
                            DirectorID = 7,
                            ImgUrl = "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_UX182_CR0,0,182,268_AL_.jpg",
                            Name = "The Dark Knight",
                            TrailerUrl = "https://www.imdb.com/title/tt0468569/videoplayer/vi324468761",
                            Year = 2008
                        },
                        new
                        {
                            ID = 8,
                            Description = "A cowboy doll is profoundly threatened and jealous when a new spaceman figure supplants him as top toy in a boy's room.",
                            DirectorID = 9,
                            ImgUrl = "https://m.media-amazon.com/images/M/MV5BMDU2ZWJlMjktMTRhMy00ZTA5LWEzNDgtYmNmZTEwZTViZWJkXkEyXkFqcGdeQXVyNDQ2OTk4MzI@._V1_UX182_CR0,0,182,268_AL_.jpg",
                            Name = "Toy Story",
                            TrailerUrl = "https://www.imdb.com/title/tt0114709/videoplayer/vi2052129305",
                            Year = 1995
                        },
                        new
                        {
                            ID = 9,
                            Description = "Two grifters team up to pull off the ultimate con.",
                            DirectorID = 8,
                            ImgUrl = "https://m.media-amazon.com/images/M/MV5BNGU3NjQ4YTMtZGJjOS00YTQ3LThmNmItMTI5MDE2ODI3NzY3XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_UX182_CR0,0,182,268_AL_.jpg",
                            Name = "El Golpe",
                            TrailerUrl = "https://www.imdb.com/title/tt0070735/videoplayer/vi2717122841",
                            Year = 1973
                        });
                });

            modelBuilder.Entity("DevOpsDemo.Data.Models.Rating", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("ChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MovieID")
                        .HasColumnType("int");

                    b.Property<int>("Star")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MovieID");

                    b.ToTable("Rating");
                });

            modelBuilder.Entity("ActorMovie", b =>
                {
                    b.HasOne("DevOpsDemo.Data.Models.Actor", null)
                        .WithMany()
                        .HasForeignKey("ActorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevOpsDemo.Data.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevOpsDemo.Data.Models.Movie", b =>
                {
                    b.HasOne("DevOpsDemo.Data.Models.Director", "Director")
                        .WithMany("Movie")
                        .HasForeignKey("DirectorID");

                    b.Navigation("Director");
                });

            modelBuilder.Entity("DevOpsDemo.Data.Models.Rating", b =>
                {
                    b.HasOne("DevOpsDemo.Data.Models.Movie", "Movie")
                        .WithMany("Rating")
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("DevOpsDemo.Data.Models.Director", b =>
                {
                    b.Navigation("Movie");
                });

            modelBuilder.Entity("DevOpsDemo.Data.Models.Movie", b =>
                {
                    b.Navigation("Rating");
                });
#pragma warning restore 612, 618
        }
    }
}
